# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Node CI
on:
  push:
    branches:
    - 'master'
    paths-ignore:
    - 'build/**'
jobs:
  build-and-deploy-gh-pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Pull source code
      uses: actions/checkout@v1
      with:
        path: .
    - name: Pull Hexo Theme - Melody
      uses: actions/checkout@v1
      with:
        repository: flytreeleft/hexo-theme-melody
        ref: master
        path: themes/melody
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build with NPM
      run: |
        npm install -g yarn
        yarn install
        npm run clean
        npm run _build -- --config config.yml,github.yml
        ls -al themes/ themes/melody/
        cp README.md dist/
    # https://github.com/marketplace/actions/release-github-pages
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy Github Pages
      uses: ./.github/actions/deploy-gh-pages
      env:
        # https://github.com/peaceiris/actions-gh-pages#1-add-ssh-deploy-key
        # - ssh-keygen -t rsa -b 4096 -C "$(git config user.email)" -f gh-pages -N ""
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        GITHUB_PAGES_REPO_AUTHOR: ${{ github.actor }}
        GITHUB_PAGES_REPO_NAME: ${{ github.actor }}.github.io
        GITHUB_PAGES_RELEASE_BRANCH: master
        PROJECT_BUILD_FOLDER: dist
        GITHUB_PAGES_CLEANUP_SCRIPT: "git clean -d -f && git rm -r *"
